name: Proibir alterações no db.txt

on: 
  push:
    paths:
      - 'db.txt'  # dispara apenas se db.txt for alterado

jobs:
  check-db-txt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Checar se db.txt foi alterado
        run: |
          # Comparar todos os commits do push com a branch principal
          if git diff --name-only origin/main...HEAD | grep -q '^db.txt$'; then
            echo "Erro: Alterações no db.txt não são permitidas."
            exit 1
          else
            echo "Nenhuma alteração no db.txt detectada."
          fi
